[package]
name = "next-gen-rps"
version = "0.1.0"
authors = ["maro-9775 <maier.rom@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
